spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.allica: INFO
    org.springframework: WARN
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
    include-exception: false
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
